config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  post 'shipment/document_completed', to: 'easyship_shipments#document_completed'

  namespace :admin do
    resources :orders do
      member do
        post :buy_label
        get :shipment_status
      end
    end
  end
end

app/views/spree/admin/order/_easyship_shipment.html.erb
<tr class="vertical-middle">
  <th> Shipping Method </th>
  <% shipment = @order.shipments.first %>
  <td> <%= shipment.courier_name %> </td>
  <td> <%= "#{shipment.currency} #{shipment.cost}" %> </td>
  <td colspan="2"> Label Status: <%= shipment.shipping_label_state.try(:titleize) || "Not Created" %> </td>
  <td class="actions">
    <% if @order.completed? %>
      <% if shipment.shipping_label_state.nil? %>
        <%= button_to 'Buy Label', buy_label_admin_order_path(@order) %><br>
      <% end %>
      <% if shipment.easyship_shipment_id.present? %>
        <%= button_to 'Update Shipping Status', shipment_status_admin_order_path(@order), { method: :get, params: { easyship_shipment_id: shipment.easyship_shipment_id } } %>  
      <% end %>
    <% end %>
  </td>
</tr>
<tr class="vertical-middle">
  <th> Easyship Label URL </th>
  <td colspan="5"> <%= shipment.shipping_label_url %> </td>
</tr>

app/views/spree/admin/order/_easyship_shipment_tracking.html.erb
<tr class="vertical-middle">
  <th> Tracking Number </th>
  <% shipment = order.shipments.first %>
  <td colspan="5"> <%= shipment.tracking_number || 'No tracking details provided.' %> </td>
</tr>
<tr class="vertical-middle">
  <th> Tracking URL </th>
  <td colspan="5"> <%= shipment.tracking_url %> </td>
</tr>